# Generated by Django 4.2.3 on 2023-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='', upload_to='profile_pic')),
                ('usertype', models.CharField(default='buyer', max_length=100)),
            ],
        ),
    ]
